# Generated by Django 3.0.3 on 2023-07-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcamera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedulas',
            old_name='numero',
            new_name='cedula',
        ),
    ]
